// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-access_token'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MenuItemTypeSchema = {
    type: 'string',
    enum: ['tab', 'link', 'iframe'],
    title: 'MenuItemType'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const OperationLogPublicSchema = {
    properties: {
        user_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        },
        username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        request_method: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Request Method'
        },
        request_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Request Path'
        },
        request_query_params: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Request Query Params'
        },
        response_status_code: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Response Status Code'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'created_at'],
    title: 'OperationLogPublic'
} as const;

export const OperationLogsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/OperationLogPublic'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['data', 'total'],
    title: 'OperationLogsPublic'
} as const;

export const OrderDirectionSchema = {
    type: 'string',
    enum: ['asc', 'desc'],
    title: 'OrderDirection'
} as const;

export const PermissionSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name', 'description'],
    title: 'Permission'
} as const;

export const RoleCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        permissions: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Permissions'
        },
        users: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Users'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'RoleCreate'
} as const;

export const RolePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        permissions: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/RoleRule'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Permissions'
        },
        users: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/RoleUser'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Users'
        }
    },
    type: 'object',
    required: ['name', 'id', 'created_at', 'updated_at'],
    title: 'RolePublic'
} as const;

export const RoleRuleSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        }
    },
    type: 'object',
    required: ['id', 'name', 'title', 'parent_id'],
    title: 'RoleRule'
} as const;

export const RoleUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        permissions: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Permissions'
        },
        users: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Users'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'RoleUpdate'
} as const;

export const RoleUserSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        username: {
            type: 'string',
            title: 'Username'
        }
    },
    type: 'object',
    required: ['id', 'username'],
    title: 'RoleUser'
} as const;

export const RolesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RolePublic'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['data', 'total'],
    title: 'RolesPublic'
} as const;

export const RuleCreateSchema = {
    properties: {
        parent_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        type: {
            '$ref': '#/components/schemas/RuleType'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        name: {
            type: 'string',
            title: 'Name',
            description: '将注册为前端路由名称，同时用作前后端鉴权。当type=RuleType.permission时，name和对应的后端接口权限名一致。'
        },
        path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Path'
        },
        icon: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon'
        },
        menu_item_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MenuItemType'
                },
                {
                    type: 'null'
                }
            ]
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        component: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Component'
        },
        remark: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remark'
        },
        cache: {
            type: 'boolean',
            title: 'Cache',
            default: false
        },
        weight: {
            type: 'integer',
            title: 'Weight',
            default: 0
        },
        status: {
            type: 'boolean',
            title: 'Status',
            default: true
        }
    },
    type: 'object',
    required: ['type', 'title', 'name'],
    title: 'RuleCreate'
} as const;

export const RuleTreePublicSchema = {
    properties: {
        parent_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        type: {
            '$ref': '#/components/schemas/RuleType'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        name: {
            type: 'string',
            title: 'Name',
            description: '将注册为前端路由名称，同时用作前后端鉴权。当type=RuleType.permission时，name和对应的后端接口权限名一致。'
        },
        path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Path'
        },
        icon: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon'
        },
        menu_item_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MenuItemType'
                },
                {
                    type: 'null'
                }
            ]
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        component: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Component'
        },
        remark: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remark'
        },
        cache: {
            type: 'boolean',
            title: 'Cache',
            default: false
        },
        weight: {
            type: 'integer',
            title: 'Weight',
            default: 0
        },
        status: {
            type: 'boolean',
            title: 'Status',
            default: true
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        children: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/RuleTreePublic'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Children'
        }
    },
    type: 'object',
    required: ['type', 'title', 'name', 'id', 'created_at', 'updated_at'],
    title: 'RuleTreePublic'
} as const;

export const RuleTreesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RuleTreePublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'RuleTreesPublic'
} as const;

export const RuleTypeSchema = {
    type: 'string',
    enum: ['menu_dir', 'menu_item', 'permission'],
    title: 'RuleType'
} as const;

export const RuleUpdateSchema = {
    properties: {
        parent_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/RuleType'
                },
                {
                    type: 'null'
                }
            ]
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Path'
        },
        icon: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon'
        },
        menu_item_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MenuItemType'
                },
                {
                    type: 'null'
                }
            ]
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        component: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Component'
        },
        remark: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remark'
        },
        cache: {
            type: 'boolean',
            title: 'Cache',
            default: false
        },
        weight: {
            type: 'integer',
            title: 'Weight',
            default: 0
        },
        status: {
            type: 'boolean',
            title: 'Status',
            default: true
        }
    },
    type: 'object',
    title: 'RuleUpdate'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UserBehaviorCountSchema = {
    properties: {
        dt: {
            type: 'string',
            format: 'date',
            title: 'Dt'
        },
        behavior: {
            type: 'string',
            title: 'Behavior'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['dt', 'behavior', 'count'],
    title: 'UserBehaviorCount'
} as const;

export const UserCreateSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 50,
            minLength: 2,
            title: 'Username'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        source: {
            '$ref': '#/components/schemas/UserSource',
            default: 'system'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        },
        roles: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Roles'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'UserCreate'
} as const;

export const UserHomeSchema = {
    properties: {
        logins_1w: {
            type: 'integer',
            title: 'Logins 1W',
            default: 0
        },
        previous_logins_1w: {
            type: 'integer',
            title: 'Previous Logins 1W',
            default: 0
        },
        logins_1m: {
            type: 'integer',
            title: 'Logins 1M',
            default: 0
        },
        previous_logins_1m: {
            type: 'integer',
            title: 'Previous Logins 1M',
            default: 0
        },
        operations_1w: {
            type: 'integer',
            title: 'Operations 1W',
            default: 0
        },
        previous_operations_1w: {
            type: 'integer',
            title: 'Previous Operations 1W',
            default: 0
        },
        operations_1m: {
            type: 'integer',
            title: 'Operations 1M',
            default: 0
        },
        previous_operations_1m: {
            type: 'integer',
            title: 'Previous Operations 1M',
            default: 0
        },
        behavior_1w: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/UserBehaviorCount'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Behavior 1W'
        },
        behavior_1m: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/UserBehaviorCount'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Behavior 1M'
        },
        menus: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/UserMenuCount'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Menus'
        }
    },
    type: 'object',
    title: 'UserHome'
} as const;

export const UserMePublicSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 50,
            minLength: 2,
            title: 'Username'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        source: {
            '$ref': '#/components/schemas/UserSource',
            default: 'system'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        last_login_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Login At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        roles: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/UserRole'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Roles'
        },
        rules: {
            items: {
                '$ref': '#/components/schemas/UserRuleTreePublic'
            },
            type: 'array',
            title: 'Rules',
            default: []
        }
    },
    type: 'object',
    required: ['username', 'id', 'created_at', 'updated_at'],
    title: 'UserMePublic'
} as const;

export const UserMenuCountSchema = {
    properties: {
        menu: {
            type: 'string',
            title: 'Menu'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['menu', 'count'],
    title: 'UserMenuCount'
} as const;

export const UserPublicSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 50,
            minLength: 2,
            title: 'Username'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        source: {
            '$ref': '#/components/schemas/UserSource',
            default: 'system'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        last_login_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Login At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        roles: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/UserRole'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Roles'
        }
    },
    type: 'object',
    required: ['username', 'id', 'created_at', 'updated_at'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 50,
            minLength: 2,
            title: 'Username'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'UserRegister'
} as const;

export const UserRoleSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'UserRole'
} as const;

export const UserRuleTreePublicSchema = {
    properties: {
        parent_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        type: {
            '$ref': '#/components/schemas/RuleType'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        name: {
            type: 'string',
            title: 'Name',
            description: '将注册为前端路由名称，同时用作前后端鉴权。当type=RuleType.permission时，name和对应的后端接口权限名一致。'
        },
        path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Path'
        },
        icon: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon'
        },
        menu_item_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MenuItemType'
                },
                {
                    type: 'null'
                }
            ]
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        component: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Component'
        },
        remark: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remark'
        },
        cache: {
            type: 'boolean',
            title: 'Cache',
            default: false
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        children: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/UserRuleTreePublic'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Children'
        }
    },
    type: 'object',
    required: ['type', 'title', 'name', 'id'],
    title: 'UserRuleTreePublic'
} as const;

export const UserSourceSchema = {
    type: 'string',
    enum: ['system', 'signup'],
    title: 'UserSource'
} as const;

export const UserUpdateSchema = {
    properties: {
        username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50,
                    minLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        source: {
            '$ref': '#/components/schemas/UserSource',
            default: 'system'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        roles: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Roles'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['data', 'total'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;