// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { LoginAccessTokenData, LoginAccessTokenResponse, LoginTestTokenResponse, OperationLogsReadOperationLogsData, OperationLogsReadOperationLogsResponse, OperationLogsSubmitOperationLogData, OperationLogsSubmitOperationLogResponse, OperationLogsReadOperationLogByIdData, OperationLogsReadOperationLogByIdResponse, OperationLogsDeleteOperationLogData, OperationLogsDeleteOperationLogResponse, RolesReadRolesData, RolesReadRolesResponse, RolesCreateRoleData, RolesCreateRoleResponse, RolesReadRoleData, RolesReadRoleResponse, RolesUpdateRoleData, RolesUpdateRoleResponse, RolesDeleteRoleData, RolesDeleteRoleResponse, RulesReadRulesData, RulesReadRulesResponse, RulesCreateRuleData, RulesCreateRuleResponse, RulesReadPermissionsData, RulesReadPermissionsResponse, RulesReadRuleData, RulesReadRuleResponse, RulesUpdateRuleData, RulesUpdateRuleResponse, RulesDeleteRuleData, RulesDeleteRuleResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserHomeResponse, UsersReadUserOperationLogsData, UsersReadUserOperationLogsResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsHealthCheckResponse } from './types.gen';

export class LoginService {
    /**
     * Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static accessToken(data: LoginAccessTokenData): CancelablePromise<LoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
}

export class OperationLogsService {
    /**
     * Read Operation Logs
     * Read operation logs
     * @param data The data for the request.
     * @param data.quickSearch Quick search
     * @param data.skip
     * @param data.limit
     * @param data.orderBy
     * @param data.orderDirection
     * @param data.commonSearch
     * @returns OperationLogsPublic Successful Response
     * @throws ApiError
     */
    public static readOperationLogs(data: OperationLogsReadOperationLogsData = {}): CancelablePromise<OperationLogsReadOperationLogsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/operation-logs/',
            query: {
                quick_search: data.quickSearch,
                skip: data.skip,
                limit: data.limit,
                order_by: data.orderBy,
                order_direction: data.orderDirection,
                common_search: data.commonSearch
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Submit Operation Log
     * Proactively submit operation log. eg: Trigger the API to record operational logs upon accessing links or iframe menus in the frontend.
     * @param data The data for the request.
     * @param data.ruleName
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static submitOperationLog(data: OperationLogsSubmitOperationLogData): CancelablePromise<OperationLogsSubmitOperationLogResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/operation-logs/submit',
            query: {
                rule_name: data.ruleName
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Operation Log By Id
     * Read a specific operation log by id.
     * @param data The data for the request.
     * @param data.id
     * @returns OperationLogPublic Successful Response
     * @throws ApiError
     */
    public static readOperationLogById(data: OperationLogsReadOperationLogByIdData): CancelablePromise<OperationLogsReadOperationLogByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/operation-logs/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Operation Log
     * Delete a specific operation log.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteOperationLog(data: OperationLogsDeleteOperationLogData): CancelablePromise<OperationLogsDeleteOperationLogResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/operation-logs/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class RolesService {
    /**
     * Read Roles
     * Read roles.
     * @param data The data for the request.
     * @param data.quickSearch Quick search
     * @param data.skip
     * @param data.limit
     * @param data.orderBy
     * @param data.orderDirection
     * @returns RolesPublic Successful Response
     * @throws ApiError
     */
    public static readRoles(data: RolesReadRolesData = {}): CancelablePromise<RolesReadRolesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/roles/',
            query: {
                quick_search: data.quickSearch,
                skip: data.skip,
                limit: data.limit,
                order_by: data.orderBy,
                order_direction: data.orderDirection
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Role
     * Create new role.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static createRole(data: RolesCreateRoleData): CancelablePromise<RolesCreateRoleResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/roles/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Role
     * Read a role by id.
     * @param data The data for the request.
     * @param data.id
     * @returns RolePublic Successful Response
     * @throws ApiError
     */
    public static readRole(data: RolesReadRoleData): CancelablePromise<RolesReadRoleResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/roles/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Role
     * Update a role.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updateRole(data: RolesUpdateRoleData): CancelablePromise<RolesUpdateRoleResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/roles/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Role
     * Delete a role.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteRole(data: RolesDeleteRoleData): CancelablePromise<RolesDeleteRoleResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/roles/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class RulesService {
    /**
     * Read Rules
     * Read rules.
     * @param data The data for the request.
     * @param data.onlyMenus Only return menus
     * @param data.quickSearch Quick search
     * @returns RuleTreesPublic Successful Response
     * @throws ApiError
     */
    public static readRules(data: RulesReadRulesData = {}): CancelablePromise<RulesReadRulesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/rules/',
            query: {
                only_menus: data.onlyMenus,
                quick_search: data.quickSearch
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Rule
     * Create new rule.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static createRule(data: RulesCreateRuleData): CancelablePromise<RulesCreateRuleResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/rules/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Permissions
     * Read permissions.
     * @param data The data for the request.
     * @param data.unassigned Unassigned to rule
     * @returns Permission Successful Response
     * @throws ApiError
     */
    public static readPermissions(data: RulesReadPermissionsData = {}): CancelablePromise<RulesReadPermissionsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/rules/permissions',
            query: {
                unassigned: data.unassigned
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Rule
     * Read a rule by id.
     * @param data The data for the request.
     * @param data.id
     * @returns RuleTreePublic Successful Response
     * @throws ApiError
     */
    public static readRule(data: RulesReadRuleData): CancelablePromise<RulesReadRuleResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/rules/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Rule
     * Update an rule.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updateRule(data: RulesUpdateRuleData): CancelablePromise<RulesUpdateRuleResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/rules/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Rule
     * Delete an rule.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteRule(data: RulesDeleteRuleData): CancelablePromise<RulesDeleteRuleResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/rules/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Read users
     * @param data The data for the request.
     * @param data.quickSearch Quick search
     * @param data.skip
     * @param data.limit
     * @param data.orderBy
     * @param data.orderDirection
     * @param data.commonSearch
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                quick_search: data.quickSearch,
                skip: data.skip,
                limit: data.limit,
                order_by: data.orderBy,
                order_direction: data.orderDirection,
                common_search: data.commonSearch
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Home
     * Read current user home data.
     * @returns UserHome Successful Response
     * @throws ApiError
     */
    public static readUserHome(): CancelablePromise<UsersReadUserHomeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/home'
        });
    }
    
    /**
     * Read User Operation Logs
     * Read current user operation logs.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns OperationLogsPublic Successful Response
     * @throws ApiError
     */
    public static readUserOperationLogs(data: UsersReadUserOperationLogsData = {}): CancelablePromise<UsersReadUserOperationLogsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/operation-logs',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Read current user.
     * @returns UserMePublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Read a specific user by id.
     * @param data The data for the request.
     * @param data.id
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/users/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Health Check
     * Health check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}