// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type MenuItemType = 'tab' | 'link' | 'iframe';

export type Message = {
    message: string;
};

export type OperationLogPublic = {
    user_id?: (number | null);
    username?: (string | null);
    name?: (string | null);
    title?: (string | null);
    request_method?: (string | null);
    request_path?: (string | null);
    request_query_params?: (string | null);
    response_status_code?: (number | null);
    id: string;
    created_at: string;
};

export type OperationLogsPublic = {
    data: Array<OperationLogPublic>;
    total: number;
};

export type OrderDirection = 'asc' | 'desc';

export type Permission = {
    name: string;
    description: string;
};

export type RoleCreate = {
    name: string;
    permissions?: (Array<(number)> | null);
    users?: (Array<(number)> | null);
};

export type RolePublic = {
    name: string;
    id: number;
    created_at: string;
    updated_at: string;
    permissions?: (Array<RoleRule> | null);
    users?: (Array<RoleUser> | null);
};

export type RoleRule = {
    id: number;
    name: string;
    title: string;
    parent_id: (number | null);
};

export type RolesPublic = {
    data: Array<RolePublic>;
    total: number;
};

export type RoleUpdate = {
    name: string;
    permissions?: (Array<(number)> | null);
    users?: (Array<(number)> | null);
};

export type RoleUser = {
    id: number;
    username: string;
};

export type RuleCreate = {
    parent_id?: (number | null);
    type: RuleType;
    title: string;
    /**
     * 将注册为前端路由名称，同时用作前后端鉴权。当type=RuleType.permission时，name和对应的后端接口权限名一致。
     */
    name: string;
    path?: (string | null);
    icon?: (string | null);
    menu_item_type?: (MenuItemType | null);
    url?: (string | null);
    component?: (string | null);
    remark?: (string | null);
    cache?: boolean;
    weight?: number;
    status?: boolean;
};

export type RuleTreePublic = {
    parent_id?: (number | null);
    type: RuleType;
    title: string;
    /**
     * 将注册为前端路由名称，同时用作前后端鉴权。当type=RuleType.permission时，name和对应的后端接口权限名一致。
     */
    name: string;
    path?: (string | null);
    icon?: (string | null);
    menu_item_type?: (MenuItemType | null);
    url?: (string | null);
    component?: (string | null);
    remark?: (string | null);
    cache?: boolean;
    weight?: number;
    status?: boolean;
    id: number;
    created_at: string;
    updated_at: string;
    children?: (Array<RuleTreePublic> | null);
};

export type RuleTreesPublic = {
    data: Array<RuleTreePublic>;
};

export type RuleType = 'menu_dir' | 'menu_item' | 'permission';

export type RuleUpdate = {
    parent_id?: (number | null);
    type?: (RuleType | null);
    title?: (string | null);
    name?: (string | null);
    path?: (string | null);
    icon?: (string | null);
    menu_item_type?: (MenuItemType | null);
    url?: (string | null);
    component?: (string | null);
    remark?: (string | null);
    cache?: boolean;
    weight?: number;
    status?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UserBehaviorCount = {
    dt: string;
    behavior: string;
    count: number;
};

export type UserCreate = {
    username: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    source?: UserSource;
    password: string;
    roles?: (Array<(number)> | null);
};

export type UserHome = {
    logins_1w?: number;
    previous_logins_1w?: number;
    logins_1m?: number;
    previous_logins_1m?: number;
    operations_1w?: number;
    previous_operations_1w?: number;
    operations_1m?: number;
    previous_operations_1m?: number;
    behavior_1w?: (Array<UserBehaviorCount> | null);
    behavior_1m?: (Array<UserBehaviorCount> | null);
    menus?: (Array<UserMenuCount> | null);
};

export type UserMenuCount = {
    menu: string;
    count: number;
};

export type UserMePublic = {
    username: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    source?: UserSource;
    id: number;
    last_login_at?: (string | null);
    created_at: string;
    updated_at: string;
    roles?: (Array<UserRole> | null);
    rules?: Array<UserRuleTreePublic>;
};

export type UserPublic = {
    username: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    source?: UserSource;
    id: number;
    last_login_at?: (string | null);
    created_at: string;
    updated_at: string;
    roles?: (Array<UserRole> | null);
};

export type UserRegister = {
    username: string;
    password: string;
    full_name?: (string | null);
};

export type UserRole = {
    id: number;
    name: string;
};

export type UserRuleTreePublic = {
    parent_id?: (number | null);
    type: RuleType;
    title: string;
    /**
     * 将注册为前端路由名称，同时用作前后端鉴权。当type=RuleType.permission时，name和对应的后端接口权限名一致。
     */
    name: string;
    path?: (string | null);
    icon?: (string | null);
    menu_item_type?: (MenuItemType | null);
    url?: (string | null);
    component?: (string | null);
    remark?: (string | null);
    cache?: boolean;
    id: number;
    children?: (Array<UserRuleTreePublic> | null);
};

export type UserSource = 'system' | 'signup';

export type UsersPublic = {
    data: Array<UserPublic>;
    total: number;
};

export type UserUpdate = {
    username?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    source?: UserSource;
    password?: (string | null);
    roles?: (Array<(number)> | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    password?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginAccessTokenData = {
    formData: Body_login_access_token;
};

export type LoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type OperationLogsReadOperationLogsData = {
    commonSearch?: (string | null);
    limit?: number;
    orderBy?: (string | null);
    orderDirection?: OrderDirection;
    /**
     * Quick search
     */
    quickSearch?: string;
    skip?: number;
};

export type OperationLogsReadOperationLogsResponse = (OperationLogsPublic);

export type OperationLogsSubmitOperationLogData = {
    ruleName: string;
};

export type OperationLogsSubmitOperationLogResponse = (Message);

export type OperationLogsReadOperationLogByIdData = {
    id: string;
};

export type OperationLogsReadOperationLogByIdResponse = (OperationLogPublic);

export type OperationLogsDeleteOperationLogData = {
    id: string;
};

export type OperationLogsDeleteOperationLogResponse = (Message);

export type RolesReadRolesData = {
    limit?: number;
    orderBy?: (string | null);
    orderDirection?: OrderDirection;
    /**
     * Quick search
     */
    quickSearch?: string;
    skip?: number;
};

export type RolesReadRolesResponse = (RolesPublic);

export type RolesCreateRoleData = {
    requestBody: RoleCreate;
};

export type RolesCreateRoleResponse = (Message);

export type RolesReadRoleData = {
    id: number;
};

export type RolesReadRoleResponse = (RolePublic);

export type RolesUpdateRoleData = {
    id: number;
    requestBody: RoleUpdate;
};

export type RolesUpdateRoleResponse = (Message);

export type RolesDeleteRoleData = {
    id: number;
};

export type RolesDeleteRoleResponse = (Message);

export type RulesReadRulesData = {
    /**
     * Only return menus
     */
    onlyMenus?: boolean;
    /**
     * Quick search
     */
    quickSearch?: string;
};

export type RulesReadRulesResponse = (RuleTreesPublic);

export type RulesCreateRuleData = {
    requestBody: RuleCreate;
};

export type RulesCreateRuleResponse = (Message);

export type RulesReadPermissionsData = {
    /**
     * Unassigned to rule
     */
    unassigned?: boolean;
};

export type RulesReadPermissionsResponse = (Array<Permission>);

export type RulesReadRuleData = {
    id: number;
};

export type RulesReadRuleResponse = (RuleTreePublic);

export type RulesUpdateRuleData = {
    id: number;
    requestBody: RuleUpdate;
};

export type RulesUpdateRuleResponse = (Message);

export type RulesDeleteRuleData = {
    id: number;
};

export type RulesDeleteRuleResponse = (Message);

export type UsersReadUsersData = {
    commonSearch?: (string | null);
    limit?: number;
    orderBy?: (string | null);
    orderDirection?: OrderDirection;
    /**
     * Quick search
     */
    quickSearch?: string;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (Message);

export type UsersReadUserHomeResponse = (UserHome);

export type UsersReadUserOperationLogsData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUserOperationLogsResponse = (OperationLogsPublic);

export type UsersReadUserMeResponse = (UserMePublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (Message);

export type UsersReadUserByIdData = {
    id: number;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    id: number;
    requestBody: UserUpdate;
};

export type UsersUpdateUserResponse = (Message);

export type UsersDeleteUserData = {
    id: number;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);